#!/usr/bin/perl -w
use strict;

my $n_steps=32;
my $n_prot_atoms=2125;
my $d_lambda=0.002;

my $solvent_group="Water";
my $solute_group="Protein";

######### pmf_skeletor_space ###########################
die unless(-e "pmf_skeletor_space");
system "mv pmf_skeletor_space tmp_file";
open(INP,"tmp_file") or die;
open(OUT,">pmf_skeletor_space");
while(<INP>) {
  if (/^my \$n_steps/) {
    print OUT "my \$n_steps = $n_steps;\n";
    next;
  }
  if (/^my \$n_prot_atoms/) {
    print OUT "my \$n_prot_atoms = $n_prot_atoms;\n";
    next;
  }

  if (/^my \$solvent_group/) {
    print OUT "my \$solvent_group = \"$solvent_group\";\n";
    next;
  }
  if (/^my \$solute_group/) {
    print OUT "my \$solute_group = \"$solute_group\";\n";
    next;
  } 

  print OUT $_;
  
}
close INP;
close OUT;
system "chmod +x pmf_skeletor_space";
system "rm tmp_file";

######### pmf_re_runner ###########################
die unless(-e "pmf_re_runner");
system "mv pmf_re_runner tmp_file";
open(INP,"tmp_file") or die;
open(OUT,">pmf_re_runner");
while(<INP>) {
  if (/^my \$n_steps/) {
    print OUT "my \$n_steps = $n_steps;\n";
    next;
  }
  print OUT $_;
  
}
close INP;
close OUT;
system "chmod +x pmf_re_runner";
system "rm tmp_file";

######### make_ti_ew ###########################
die unless(-e "make_ti_ew");
system "mv make_ti_ew tmp_file";
open(INP,"tmp_file") or die;
open(OUT,">make_ti_ew");
while(<INP>) {
  if (/^my \$n_steps/) {
    print OUT "my \$n_steps = $n_steps;\n";
    next;
  }
  if (/^my \$n_prot_atoms/) {
    print OUT "my \$n_prot_atoms = $n_prot_atoms;\n";
    next;
  }
  if (/^my \$d_lambda/) {
    print OUT "my \$d_lambda = $d_lambda;\n";
    next;
  }

  print OUT $_;
  
}
close INP;
close OUT;
system "chmod +x make_ti_ew";
system "rm tmp_file";

######### make_ti_boots ###########################
die unless(-e "make_ti_boots");
system "mv make_ti_boots tmp_file";
open(INP,"tmp_file") or die;
open(OUT,">make_ti_boots");
while(<INP>) {
  if (/^my \$n_steps/) {
    print OUT "my \$n_steps = $n_steps;\n";
    next;
  }

  if (/^my \$d_lambda/) {
    print OUT "my \$d_lambda = $d_lambda;\n";
    next;
  }

  print OUT $_;
  
}
close INP;
close OUT;
system "chmod +x make_ti_boots";
system "rm tmp_file";

###########################################################
system "./pmf_skeletor_space";
system "./pmf_re_runner";
system "./make_ti_ew";
system "./make_ti_boots > ti_results.dat";
